#server:
#  port: 9999
#spring:
#  application:
#    name: bookstore
#  datasource:
#    url: jdbc:mysql://localhost:3306/bookstore
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: none
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: true
#    show-sql: true
#
#
